# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dessert_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dessert_name', to='myapp.dessert'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dessert_shop_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_name', to='myapp.dessert_shop'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='myapp.user'),
        ),
    ]
