# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170527_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dessert_name',
            field=models.CharField(max_length=100, verbose_name=myapp.models.dessert),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(max_length=100, verbose_name=myapp.models.user),
        ),
    ]
