# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170527_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dessert_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dessert_shop_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
