# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20170531_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='dessertid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dessert_shop',
            name='phonenumber',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dessert_shop',
            name='shopid',
            field=models.IntegerField(max_length=100),
        ),
    ]
