# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20170531_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dessert',
            name='shops',
        ),
        migrations.AddField(
            model_name='dessert',
            name='shop',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dessert_shop',
            name='shopid',
            field=models.CharField(max_length=100),
        ),
    ]
