# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20170601_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dessert',
            old_name='shops',
            new_name='itshop',
        ),
    ]
